from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    STATUS_CHOICES = [('draft', 'Draft'), ('published', 'Published')]
    
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    # slug = forms.SlugField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'slug-is-autogenerated'}), required=False)
    # author = forms.ModelChoiceField(queryset=User.objects.all(), widget=forms.Select(attrs={'class': 'form-control'}))
    body = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'This blog supports Markdown format...'}))
    # tags = forms.CharF
    tags = forms.TextInput(attrs={'class': 'form-control'}),
    # ield(widget=forms.TextInput(attrs={'class': 'form-control'}))
    status = forms.ChoiceField(choices=STATUS_CHOICES, widget=forms.Select(attrs={'class': 'form-control'}))
    
    # Add a DateTimeField for publish date and time
    # publish = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'class': 'form-control'}))

    # widgets = {
    # #         'title': forms.TextInput(attrs={'class': 'form-control'}),
    # #         'slug': forms.TextInput(attrs={'class': 'form-control'}),
    # #         # 'author': forms.Select(attrs={'class': 'form-control'}),
    # #         'body': forms.Textarea(attrs={'class': 'form-control'}),
    #         'tags': forms.TextInput(attrs={'class': 'form-control'}),
    #     }

    class Meta:
        model = Post
        # fields = ['title', 'slug', 'author', 'body', 'tags', 'status', 'publish']
        # fields = ['title', 'author', 'body', 'tags', 'status', 'publish']
        fields = ['title', 'body', 'tags', 'status', 'publish']
    # status = forms.ChoiceField(choices=Post.STATUS_CHOICES, widget=forms.Select(attrs={'class': 'form-control'}))

    # class Meta:
    #     model = Post
    #     # fields = ['title', 'slug', 'author', 'body', 'tags']
    #     fields = ['title', 'slug', 'body', 'tags']

    #     labels = {
    #         'title': 'Title',
    #         'slug': 'Slug',
    #         # 'author': 'Author',
    #         'body': 'Body',
    #         'tags': 'Tags',
    #         'status': 'Status',
    #     }

    #     widgets = {
    #         'title': forms.TextInput(attrs={'class': 'form-control'}),
    #         'slug': forms.TextInput(attrs={'class': 'form-control'}),
    #         # 'author': forms.Select(attrs={'class': 'form-control'}),
    #         'body': forms.Textarea(attrs={'class': 'form-control'}),
    #         'tags': forms.TextInput(attrs={'class': 'form-control'}),
    #     }

    #  # Specify that the slug field is not required
    # slug = forms.SlugField(required=False)